### ISSUE TITLE
service.url disappearing

### ISSUE THREAD

**Issue by agrechin** [hpreston/nso-netbox#1]
Thank you for sharing this service. 

I also hit `service.url` parameter disappearance:
https://github.com/hpreston/nso-netbox/blob/75d3f614d5ed3d5db03c5af7cba03ca317bb55c0/python/nso_netbox/main.py#L21-L27

You may change this default behavior of CDB on the model level. Add cdb-oper tailf extensions for operational data to make it persistent like this:

```yaml
leaf url {
    type string;
    config false;
    tailf:cdb-oper {
        tailf:persistent true;
    }
    tailf:info "Crafted URL for NetBox server";
}
```

**Comment by hpreston** [comment]
Thanks for the issue.. I've updated the service to address.
